<<<<<<< HEAD
# Generated by Django 4.2.23 on 2026-01-25 06:11
=======
# Generated by Django 4.2.7 on 2026-01-30 01:29
>>>>>>> 2079676d996d28a76ca5943a7cef4fc25b52fd5f

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True, verbose_name='Item Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Category')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('date', models.DateField(help_text='Date when stock is added', verbose_name='Date')),
                ('transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction')),
                ('requester_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Requester')),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date for perishable items (e.g., Service Perks)', null=True, verbose_name='Expiration Date')),
                ('opening_balance', models.IntegerField(default=0, verbose_name='Opening Balance')),
                ('cost_per_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cost per Item')),
                ('stock_in', models.IntegerField(default=0, verbose_name='Stock-In (Replenish)')),
                ('running_count', models.IntegerField(default=0, verbose_name='Running Count')),
                ('running_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Running Cost')),
                ('total_released', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Released')),
                ('real_time_balance', models.IntegerField(default=0, verbose_name='Real-Time Balance')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='inventory.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'db_table': 'supplies_tbl',
                'ordering': ['date', 'item_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of request', verbose_name='Date')),
                ('transaction_no', models.CharField(help_text='Transaction number (e.g., TR-0001)', max_length=100, unique=True, verbose_name='Transaction No.')),
                ('requester_name', models.CharField(help_text='Full name of the person requesting supplies', max_length=200, verbose_name='Name of Requester')),
                ('item_code', models.CharField(max_length=100, verbose_name='Item Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Category')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('quantity', models.IntegerField(default=1, help_text='Requested quantity', verbose_name='Qty')),
                ('cost_per_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cost per Item')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Cost')),
                ('stock_in_out', models.CharField(choices=[('stock-in', 'Stock-In'), ('stock-out', 'Stock-Out')], default='stock-out', max_length=20, verbose_name='Stock In-Out')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('Out of Stocks', 'Out of Stocks')], default='pending', max_length=20, verbose_name='Status')),
                ('conforme_by', models.CharField(blank=True, help_text='Name of person who approved/conformed the request', max_length=200, null=True, verbose_name='Conforme By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_request_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_supplies', to='inventory.category', verbose_name='Main Category')),
                ('supply', models.ForeignKey(blank=True, help_text='Linked inventory item in supplies_tbl', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.supply', verbose_name='Supply Item')),
            ],
            options={
                'verbose_name': 'Request Supply',
                'verbose_name_plural': 'Request Supplies',
                'db_table': 'Request_supplies_tbl',
                'ordering': ['date', 'item_code', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['item_code'], name='supplies_tb_item_co_0e68f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['main_category'], name='supplies_tb_main_ca_1edfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['date'], name='supplies_tb_date_dd9a01_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsupply',
            index=models.Index(fields=['transaction_no'], name='Request_sup_transac_5ec61d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsupply',
            index=models.Index(fields=['date'], name='Request_sup_date_826152_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsupply',
            index=models.Index(fields=['status'], name='Request_sup_status_a42737_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsupply',
            index=models.Index(fields=['requester_name'], name='Request_sup_request_bc23e4_idx'),
        ),
    ]
