# Generated by Django 4.2.23 on 2026-03-28 15:58

from django.db import migrations, models


def seed_default_prepared_by(apps, schema_editor):
    BinCardPreparedBy = apps.get_model('inventory', 'BinCardPreparedBy')
    if BinCardPreparedBy.objects.exists():
        return
    BinCardPreparedBy.objects.create(name='MICHELLE A. SILAGAN', position='', sort_order=0)
    BinCardPreparedBy.objects.create(name='FEBIE S. DE GUZMAN', position='', sort_order=1)


def unseed_default_prepared_by(apps, schema_editor):
    BinCardPreparedBy = apps.get_model('inventory', 'BinCardPreparedBy')
    BinCardPreparedBy.objects.filter(
        name__in=['MICHELLE A. SILAGAN', 'FEBIE S. DE GUZMAN']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCardPreparedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position / Title')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bin Card Prepared By',
                'verbose_name_plural': 'Bin Card Prepared By',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_default_prepared_by, unseed_default_prepared_by),
    ]
