# Generated by Django 4.2.29 on 2026-03-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(max_length=100, unique=True, verbose_name='Property Number')),
                ('equipment_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('UPS', 'UPS'), ('Switch/Hub', 'Switch/Hub'), ('Router', 'Router'), ('Monitor', 'Monitor'), ('Keyboard/Mouse', 'Keyboard/Mouse'), ('Other', 'Other')], max_length=50, verbose_name='Type of Equipment')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand / Make')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serial Number')),
                ('processor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Processor')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='RAM')),
                ('storage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage / HDD')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Date Acquired')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Acquisition Cost (₱)')),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assigned To')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='Department / Office')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('For Repair', 'For Repair'), ('For Disposal', 'For Disposal'), ('Disposed', 'Disposed'), ('Lost', 'Lost')], default='Active', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_it_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Asset',
                'verbose_name_plural': 'IT Assets',
                'db_table': 'it_assets_tbl',
                'ordering': ['-created_at'],
            },
        ),
    ]
