# Generated by Django 4.2.23 on 2026-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bincard_prepared_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCardNotedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position / Title')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bin Card Noted By',
                'verbose_name_plural': 'Bin Card Noted By',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
