# Generated by Django 4.2.29 on 2026-03-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_itasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics_number', models.CharField(max_length=50, unique=True, verbose_name='ICS Number')),
                ('ics_date', models.DateField(blank=True, null=True, verbose_name='ICS Date')),
                ('property_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Property Number')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serial Number')),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Furniture', 'Furniture'), ('Office Equipment', 'Office Equipment'), ('Vehicle', 'Vehicle'), ('Communication Equipment', 'Communication Equipment'), ('Other', 'Other')], default='Computer', max_length=100, verbose_name='Category')),
                ('asset_name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Date Acquired')),
                ('tech_specs', models.TextField(blank=True, null=True, verbose_name='Technical Specifications')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Unit Value (₱)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Value (₱)')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location')),
                ('end_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='End User')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier')),
                ('order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order No')),
                ('delivery_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery No')),
                ('iar_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='IAR No')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ppe_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PPE Asset',
                'verbose_name_plural': 'PPE Assets',
                'db_table': 'ppe_assets_tbl',
                'ordering': ['-created_at'],
            },
        ),
    ]
