# Generated by Django 4.2.29 on 2026-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ppeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppeasset',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ppe_assets/pdf/', verbose_name='Uploaded PDF'),
        ),
        migrations.DeleteModel(
            name='ITAsset',
        ),
    ]
