# Generated by Django 4.2.23 on 2026-03-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bincard_noted_by'),
        ('inventory', '0004_ppeasset_pdf_file_delete_itasset'),
    ]

    operations = [
    ]
