# Generated by Django 4.2.23 on 2026-03-29 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_merge_20260328_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEAssetAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('assignee', models.CharField(max_length=200, verbose_name='Assignee')),
                ('previous_assignee', models.CharField(blank=True, max_length=200, verbose_name='Previous assignee')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Location')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='inventory.ppeasset', verbose_name='Asset')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_assignment_logs', to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
            ],
            options={
                'verbose_name': 'PPE Assignment Log',
                'verbose_name_plural': 'PPE Assignment Logs',
                'db_table': 'ppe_asset_assignment_log_tbl',
                'ordering': ['-logged_at'],
            },
        ),
    ]
