# Generated by Django 4.2.23 on 2026-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ppe_assignment_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppeasset',
            name='category',
            field=models.CharField(choices=[('APPLIANCES', 'APPLIANCES'), ('ELECTRONIC DEVICES', 'ELECTRONIC DEVICES'), ('FURNITURE & FIXTURES', 'FURNITURE & FIXTURES'), ('IT EQUIPMENTS', 'IT EQUIPMENTS'), ('OTHERS', 'OTHERS')], default='IT EQUIPMENTS', max_length=100, verbose_name='Category'),
        ),
    ]
