# Generated by Django 4.2.29 on 2026-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_pereportsignatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Procurement personnel',
                'verbose_name_plural': 'Procurement personnel',
                'db_table': 'procurement_personnel_tbl',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
